<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>Taptalk.WPF</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Taptalk.Core\Taptalk.Core.csproj" />
    <ProjectReference Include="..\Taptalk.Engine.Parakeet\Taptalk.Engine.Parakeet.csproj" />
    <ProjectReference Include="..\Taptalk.Engine.Whisper\Taptalk.Engine.Whisper.csproj" />
  </ItemGroup>

</Project>
